global:
  seed: 123
experiment:
  name: shift_range_small
  episodes: 20
  eval_steps: 10
  epochs: 2
  output_csv: shift_range_results.csv
  gym_mode: false
  results_root: results
environment:
  class: envs.shifting.ShiftingUnevenTwoStates  # will be enforced anyway
  name: "Shifting Uneven Two States"
  params:
    _maxp: 0.8
    _maxv: 5
    _shiftsteps: 5
    _shift_min: 0.1
    _shift_max: 1.0
    interval_min_len: 1
    interval_max_len: 20
agents:
  - class: agents.oracle.OracleAgent
    name: "Oracle"
    enabled: true
    params: {}
  - class: agents.random_agent.RandomAgent
    name: "Random"
    enabled: true
    params: {}

